# Base information
baseURL = "/"
languageCode = "en-gb"
title = "Evi1haxor"
theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Remove this when using normally
# themesDir = "../../" 
# `
[module]
  [[module.imports]]
    path = "hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "TechTrek"
  URL = "techtrek"
  weight=2

  [[menu.main]]
  name = "E1ixir"
  URL = "e1ixir"
  weight=3

  # [[menu.main]]
  # name = "Contact"
  # URL = "contact"
  # weight=4


[params]
home = "Home"
# Meta data
description = "The website of Archit Dwivedi, Junior year student at IIT Jodhpur"
author = "Archit Dwivedi"


  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "dwivedi.2@iitj.ac.in"
  address = "Jodhpur, India"
  # googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

